version: '2'

services:
  app:
    build: .
    image: smithmicro/web2py
    mem_limit: 700m
    command: uwsgi
    environment:
      - WEB2PY_PASSWORD=password
      - WEB2PY_VERSION=
  web:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./keys:/keys:ro
    depends_on:
      - app
    ports:
      - 8080:80
      - 8443:443
    mem_limit: 200m
